import csv,json,re,unicodedata
from collections import Counter,defaultdict
from datetime import datetime,timezone
from pathlib import Path
R=Path(__file__).resolve().parents[1];C=R/'docs/cleaning';A=R/'docs/institutional-action-packs';A.mkdir(parents=True,exist_ok=True);NOW=datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace('+00:00','Z');TODAY=NOW[:10]
FILES={'hotels':'data/layers/hotels.geojson','tripoliRestaurants':'data/layers/tripoli-restaurants.geojson','tripoliCafes':'data/layers/tripoli-cafes.geojson','resorts':'data/layers/tourist-villages-resorts.geojson','investment':'data/layers/tourism-investment-projects.geojson'};D={k:json.loads((R/v).read_text(encoding='utf8')) for k,v in FILES.items()};START={k:len(v['features']) for k,v in D.items()};TOTAL=sum(START.values())
def rows(path):return list(csv.DictReader(path.open(encoding='utf-8-sig')))
def write(path,fields,data):
 path.parent.mkdir(parents=True,exist_ok=True)
 with path.open('w',encoding='utf-8-sig',newline='') as f:w=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore');w.writeheader();w.writerows(data)
phase1=rows(C/'national-data-cleaning-phase-1-scorecard.csv');phase1_by={x['layer_id']:x for x in phase1}; actions=rows(C/'national-review-action-register.csv'); dup=rows(C/'national-duplicate-resolution-register.csv'); probable=[x for x in dup if x['final_classification']=='probable_duplicate']; p1=[x for x in actions if x['priority']=='P1']; p2=[x for x in actions if x['priority']=='P2']; p3=[x for x in actions if x['priority']=='P3']; IDX={k:{f['properties']['id']:f for f in v['features']} for k,v in D.items()}; all_features={f['properties']['id']:(k,f) for k,v in D.items() for f in v['features']}
changelog=[]
def change(fid,lid,kind,field,old,new,reason,evidence='derived_from_existing_fields',ref='',case='',confidence='high',auto=True,institutional=False):
 changelog.append({'change_id':f'P2-CHG-{len(changelog)+1:06d}','feature_id':fid,'layer_id':lid,'change_type':kind,'field_name':field,'old_value':json.dumps(old,ensure_ascii=False,sort_keys=True) if not isinstance(old,str) else old,'new_value':json.dumps(new,ensure_ascii=False,sort_keys=True) if not isinstance(new,str) else new,'reason':reason,'evidence_type':evidence,'evidence_reference':ref,'source_case_id':case,'confidence':confidence,'automatic_change':str(auto).lower(),'institutional_confirmation_required':str(institutional).lower(),'timestamp':NOW,'reversible':'true','notes':'No external lookup used.'})

# Probable duplicates: the same evidence was rechecked; without a new independent identifier they remain institutional cases.
prob2=[]
for x in probable:
 prob2.append(dict(x,phase_2_classification='institutional_confirmation_required',phase_2_evidence_type='insufficient_evidence',phase_2_action='retain_both',phase_2_status='open',phase_2_notes='Name and proximity do not independently prove identity; no new internal identifier found.'))

# Temporary name: retain an explicit non-official administrative label and internal-only status.
temp=[];name_corr=[]
for lid,d in D.items():
 for f in d['features']:
  p=f['properties'];n=str(p.get('name_ar') or '')
  if p.get('official_name_required') or re.search(r'تحتاج تعريف|غير مسماة|unnamed|unknown',n,re.I):
   old=n;place=p.get('municipality_ar') or p.get('city_ar') or p.get('region_ar') or 'منطقة غير محددة';short=p['id'].split('-')[-1];new=f'فرصة استثمارية غير مسماة – {place} – {short}' if lid=='investment' else f'منشأة غير مسماة – {place} – {short}'
   p.update({'original_name':old,'name_ar':new,'name_normalized_ar':re.sub(r'\s+','',new),'name_status':'temporary_administrative_label','temporary_name_status':'temporary_administrative_label','temporary_name_reason':'no_direct_official_name_in_internal_sources','official_name_required':True,'name_resolution_status':'institutional_confirmation_required','name_resolution_source':p.get('source_kml'),'name_resolution_confidence':'insufficient','publication_status':'internal_only','institutional_confirmation_required':True})
   temp.append({'feature_id':p['id'],'layer_id':lid,'old_name':old,'new_name':new,'resolution_status':'temporary_administrative_label','evidence_type':'insufficient_evidence','evidence_reference':p.get('source_kml'),'official_name_required':'true','institutional_confirmation_required':'true','notes':'Administrative label is explicitly non-official.'});name_corr.append({'feature_id':p['id'],'layer_id':lid,'original_name':old,'new_name':new,'name_cleaning_method':'temporary_administrative_label','name_cleaning_confidence':'high','evidence_reference':p.get('source_kml'),'notes':'No official name invented.'});change(p['id'],lid,'temporary_name_resolution','name_ar',old,new,'Replace ambiguous generated label with explicit non-official administrative label','insufficient_evidence',p.get('source_kml') or '',confidence='high',institutional=True)

# Weighted completeness uses tourism fields only; technical metadata has no weight.
criteria={
'hotels':['name_ar','longitude','facility_type_code','city_ar','license_status','operational_status_code','rooms','beds','phone','source'],
'tripoliRestaurants':['name_ar','longitude','facility_type_code','city_ar','phone','opening_hours','cuisine_type_ar','source'],
'tripoliCafes':['name_ar','longitude','facility_type_code','city_ar','phone','opening_hours','services_ar','source'],
'resorts':['name_ar','longitude','facility_type_code','city_ar','operational_status_code','units','capacity','services_ar','phone','source'],
'investment':['name_ar','geometry_type','investment_type_code','project_status_code','ownership_type','legal_status','site_area_m2','infrastructure_status','investment_value','implementing_entity','source']}
critical={'hotels':criteria['hotels'][:6],'tripoliRestaurants':criteria['tripoliRestaurants'][:4],'tripoliCafes':criteria['tripoliCafes'][:4],'resorts':criteria['resorts'][:5],'investment':criteria['investment'][:6]}
def available(p,k):
 v=p.get(k)
 return v not in (None,'','unknown','غير محدد','not_available','institutional_confirmation_required')
before_scores={}
for lid,d in D.items():
 for f in d['features']:
  p=f['properties'];before_scores[p['id']]=(100*sum(available(p,k) for k in criteria[lid])/len(criteria[lid]),100*sum(available(p,k) for k in critical[lid])/len(critical[lid]))

# P1 resolution/action register and publication status.
p1reg=[];closures=[];action_by_id={x['feature_id']:x for x in actions};p1ids={x['feature_id'] for x in p1}
for lid,d in D.items():
 for f in d['features']:
  p=f['properties'];fid=p['id'];oldpub=p.get('publication_status');pri=p.get('review_priority');review=p.get('review_status')=='open' or p.get('data_review_status') in ('review_required','pending_review');is_temp=bool(p.get('official_name_required'))
  if fid in p1ids:
   pub='internal_only' if lid=='investment' or is_temp else 'withheld_pending_verification';reason='P1 requires institutional confirmation';p['review_status']='institutional_action_open';p['institutional_confirmation_required']=True
   a=action_by_id[fid];p1reg.append({'case_id':a['review_case_id'],'feature_id':fid,'layer_id':lid,'name_ar':p.get('name_ar'),'p1_reason':a['review_reason_codes'],'current_classification':p.get('investment_type_code') or p.get('facility_type_code'),'current_status':p.get('project_status_code') or p.get('operational_status_code'),'evidence_type':'institutional_confirmation_required','evidence_reference':p.get('source_kml') or p.get('source'),'resolution_type':'converted_to_institutional_action','fields_changed':'publication_status|review_status','old_values':oldpub,'new_values':pub,'confidence':'high','institutional_confirmation_required':'true','responsible_entity':a['required_entity'],'publication_impact':'withheld_or_internal_only','final_review_status':'institutional_action_open','notes':'Core P1 issue remains; not marked resolved.'})
  elif review:pub='internal_only' if pri=='P2' else 'internal_ready';reason='Open review item'
  else:pub='public_ready' if p.get('data_quality_status') in ('high','verified') else 'internal_ready';reason='No blocking review; quality limitations remain disclosed'
  if is_temp:pub='internal_only';reason='Temporary administrative name requires official confirmation'
  p['publication_status']=pub;p['publication_status_reason']=reason;p['publication_status_date']=TODAY;p['publication_status_method']='phase_2_rules_v1'
  if oldpub!=pub:change(fid,lid,'publication_triage','publication_status',oldpub,pub,reason,'derived_from_existing_fields',case=action_by_id.get(fid,{}).get('review_case_id',''),institutional=fid in p1ids)
  if lid!='investment':
   old=p.get('operational_status_code');source=p.get('operational_status') or p.get('status');allowed={'operational','temporarily_closed','closed','seasonal','under_maintenance','under_construction','planned'};code=source if source in allowed else 'unknown';p['operational_status_code']=code;p['operational_status_ar']={'operational':'قائم ويعمل','temporarily_closed':'مغلق مؤقتًا','closed':'مغلق','seasonal':'موسمي','under_maintenance':'قيد الصيانة','under_construction':'قيد الإنشاء','planned':'مخطط','unknown':'غير محدد'}[code]
   if old!=code:change(fid,lid,'status_normalization','operational_status_code',old,code,'Normalize only explicit supported status; otherwise unknown','derived_from_existing_fields',confidence='high')
  fields=criteria[lid];crit=critical[lid];score=round(100*sum(available(p,k) for k in fields)/len(fields),2);cscore=round(100*sum(available(p,k) for k in crit)/len(crit),2);p['weighted_completeness_score']=score;p['critical_fields_completeness']=cscore;p['supplementary_fields_completeness']=round(100*sum(available(p,k) for k in fields if k not in crit)/max(1,len([k for k in fields if k not in crit])),2);p['completeness_method_version']='phase_2_weighted_v1';change(fid,lid,'completeness_recalculation','weighted_completeness_score',before_scores[fid][0],score,'Layer-specific tourism completeness methodology; unknown values score zero','derived_from_existing_fields')
  if lid=='investment':
   avail={};ev={};conf={}
   for k in ['ownership_type','ownership_entity','legal_status','license_status','planning_status','environmental_status','investment_value','estimated_cost','currency','site_area_m2','site_area_hectares','implementing_entity','supervising_entity','investor_name','operator_name','infrastructure_status','completion_percentage']:
    avail[k]='documented_value' if p.get(k) not in (None,'') else 'institutional_confirmation_required';ev[k]=p.get('source_kml') if p.get(k) not in (None,'') else None;conf[k]='source_provided' if p.get(k) not in (None,'') else 'insufficient'
   p['field_availability_status']=avail;p['field_evidence_source']=ev;p['field_confidence']=conf

# Evidence registers (no unsupported corrections).
class_headers=['feature_id','layer_id','old_classification','new_classification','classification_evidence','classification_source','classification_confidence','classification_method','institutional_confirmation_required','notes'];class_corr=[]
geom_headers=['feature_id','layer_id','original_geometry','new_geometry','geometry_change_type','geometry_evidence','geometry_confidence','reversible','institutional_confirmation_required','notes'];geom=[]
op=[];legal=[];link=[]
for lid,d in D.items():
 for f in d['features']:
  p=f['properties'];fid=p['id'];src=p.get('source_kml');exists=bool(src and (R/src).exists());link.append({'feature_id':fid,'layer_id':lid,'source_file':src,'source_sheet_or_section':'source_record_index','source_record_identifier':p.get('source_record_index'),'match_type':'exact_internal_match' if exists and p.get('source_record_index') is not None else 'no_internal_match','match_score':1 if exists and p.get('source_record_index') is not None else 0,'matched_fields':'source_file|source_record_index' if exists else '','conflicting_fields':'','fields_imported':'','automatic_import':'false','manual_review_required':'false' if exists else 'true','notes':'Link confirmed only; no values imported because current record already derives from this source.'})
  if lid!='investment':op.append({'feature_id':fid,'layer_id':lid,'source_status':p.get('operational_status') or p.get('status'),'operational_status_code':p.get('operational_status_code'),'operational_status_ar':p.get('operational_status_ar'),'evidence_type':'derived_from_existing_fields','evidence_reference':src,'confidence':'high','institutional_confirmation_required':str(p.get('operational_status_code')=='unknown').lower(),'notes':'Unknown does not mean closed.'})
  else:legal.append({'feature_id':fid,'name_ar':p.get('name_ar'),'field_availability_status':json.dumps(p['field_availability_status'],ensure_ascii=False),'evidence_reference':src,'ownership_status':p['field_availability_status']['ownership_type'],'legal_status':p['field_availability_status']['legal_status'],'license_status':p['field_availability_status']['license_status'],'investment_value_status':p['field_availability_status']['investment_value'],'area_status':p['field_availability_status']['site_area_m2'],'infrastructure_status':p['field_availability_status']['infrastructure_status'],'institutional_confirmation_required':str(any(v=='institutional_confirmation_required' for v in p['field_availability_status'].values())).lower(),'notes':'Missing is not interpreted as negative, unlicensed, private, or stalled.'})

# Institutional packs: one primary pack per action, supporting entities for shared tasks.
pack_defs=[('01-tourism-ministry-action-pack.csv','وزارة السياحة والصناعات التقليدية'),('02-tourism-information-center-action-pack.csv','مركز المعلومات والتوثيق السياحي'),('03-investment-department-action-pack.csv','إدارة الاستثمار'),('04-municipalities-action-pack.csv','البلديات'),('05-tourism-licensing-action-pack.csv','جهة الترخيص السياحي'),('06-state-property-action-pack.csv','مصلحة أملاك الدولة'),('07-urban-planning-action-pack.csv','مصلحة التخطيط العمراني'),('08-investment-authority-action-pack.csv','هيئة تشجيع الاستثمار'),('09-environment-action-pack.csv','جهاز حماية البيئة'),('10-utilities-infrastructure-action-pack.csv','جهات المرافق والبنية التحتية'),('11-site-owners-and-operators-action-pack.csv','الجهات المالكة والمشغلون'),('12-translation-and-naming-action-pack.csv','فريق الترجمة والتسمية')];packs={x[0]:[] for x in pack_defs};entity={x[0]:x[1] for x in pack_defs}
def choose(codes,lid):
 if 'name_review' in codes or 'translation_review' in codes:return pack_defs[11][0]
 if 'investment_legal_review' in codes or 'investment_financial_review' in codes:return pack_defs[2][0]
 if 'ownership_review' in codes:return pack_defs[5][0]
 if 'infrastructure_review' in codes:return pack_defs[9][0]
 if 'classification_review' in codes:return pack_defs[0][0]
 if 'license_review' in codes:return pack_defs[4][0]
 return pack_defs[1][0]
for i,a in enumerate(actions,1):
 fid=a['feature_id'];loc=all_features.get(fid);p=loc[1]['properties'] if loc else {};codes=a['review_reason_codes'].split('|');fn=choose(codes,a['layer_id']);packs[fn].append({'action_id':f'ACT-{i:05d}','feature_id':fid,'layer_id':a['layer_id'],'name_ar':p.get('name_ar') or a['name_ar'],'city_ar':p.get('city_ar'),'municipality_ar':p.get('municipality_ar'),'priority':a['priority'],'review_reason_codes':a['review_reason_codes'],'field_or_issue':a['issue_description'],'current_value':a['current_value'],'required_value':'verified official value or documented not_available','required_action':a['required_action'],'evidence_available':a['evidence_available'],'source_reference':p.get('source_kml') or p.get('source'),'collection_method':a['suggested_collection_method'],'verification_method':'official document, registry entry, or authorized written confirmation','responsible_entity_required':entity[fn],'supporting_entities':'وزارة السياحة؛ البلدية؛ الجهة المالكة حسب الاختصاص','deadline_category':'immediate' if a['priority']=='P1' else 'next_review_cycle','publication_impact':'blocking' if a['priority']=='P1' else 'quality','status':'open','notes':'Entity is required for completion, not asserted as the current source.'})
pack_fields=['action_id','feature_id','layer_id','name_ar','city_ar','municipality_ar','priority','review_reason_codes','field_or_issue','current_value','required_value','required_action','evidence_available','source_reference','collection_method','verification_method','responsible_entity_required','supporting_entities','deadline_category','publication_impact','status','notes']
for fn,_ in pack_defs:write(A/fn,pack_fields,packs[fn])
summary=[]
for fn,en in pack_defs:
 xs=packs[fn];pc=Counter(x['priority'] for x in xs);fields=Counter(x['field_or_issue'] for x in xs);summary.append({'entity':en,'p1_actions':pc['P1'],'p2_actions':pc['P2'],'p3_actions':pc['P3'],'total_actions':len(xs),'features_affected':len({x['feature_id'] for x in xs}),'top_missing_fields':'|'.join(x for x,_ in fields.most_common(5)),'recommended_workflow':'validate, document evidence, approve, return using response template','suggested_priority':'P1' if pc['P1'] else 'P2' if pc['P2'] else 'P3','publication_impact_count':sum(x['publication_impact']=='blocking' for x in xs)})
write(A/'phase-2-management-summary.csv',list(summary[0]),summary);(A/'phase-2-management-summary.json').write_text(json.dumps({'generated_at':NOW,'entities':summary},ensure_ascii=False,indent=2)+'\n',encoding='utf8')
(A/'README-AR.md').write_text('''# حزم الإجراءات المؤسسية — المرحلة الثانية\n\nتوزع الملفات حسب الجهة المطلوبة للاستكمال، ولا تعني أن الجهة مصدر للبيانات الحالية. تعبئ الجهة نموذج الرد مع مرجع وثيقة أو سجل رسمي وتاريخ التحقق واسم الموظف وحالة الاعتماد. الأدلة المقبولة: وثيقة رسمية، قيد سجل، مخطط معتمد، ترخيص، أو إفادة مكتوبة من جهة مخولة. يعاد الملف إلى مركز المعلومات والتوثيق السياحي، ويتولى فريق تكامل البيانات مراجعة الأدلة والدمج. يوصى بتحديث P1 فورًا، وP2 في دورة ربع سنوية، وP3 نصف سنويًا. لا يعتمد أي تغيير بلا مرجع قابل للتتبع.\n''',encoding='utf8')
response_fields=['action_id','feature_id','official_name_ar','official_name_en','verified_classification','verified_operational_status','verified_project_status','verified_license_status','verified_ownership','verified_legal_status','verified_coordinates_longitude','verified_coordinates_latitude','verified_area','verified_rooms','verified_beds','verified_units','verified_capacity','verified_phone','verified_email','verified_website','verified_responsible_entity','verification_document_reference','verification_date','verifying_officer','approval_status','official_notes'];write(A/'institutional-data-response-template.csv',response_fields,[]);(A/'institutional-data-response-instructions-ar.md').write_text('# تعليمات نموذج رد الجهات\n\nيجب الاحتفاظ بـ`action_id` و`feature_id` دون تغيير، وتعبئة القيم التي تم التحقق منها فقط. يرفق مرجع الوثيقة وتاريخ التحقق والموظف المخول. تترك الحقول غير المتحققة فارغة، ولا تستخدم كلمة «لا» للتعبير عن غياب البيانات. حالات الاعتماد المقترحة: approved، rejected، needs_more_evidence.\n',encoding='utf8')

# Write registers.
write(C/'phase-2-p1-resolution-register.csv',['case_id','feature_id','layer_id','name_ar','p1_reason','current_classification','current_status','evidence_type','evidence_reference','resolution_type','fields_changed','old_values','new_values','confidence','institutional_confirmation_required','responsible_entity','publication_impact','final_review_status','notes'],p1reg);write(C/'phase-2-temporary-name-resolution.csv',['feature_id','layer_id','old_name','new_name','resolution_status','evidence_type','evidence_reference','official_name_required','institutional_confirmation_required','notes'],temp);write(C/'phase-2-classification-corrections.csv',class_headers,class_corr);write(C/'phase-2-name-corrections.csv',['feature_id','layer_id','original_name','new_name','name_cleaning_method','name_cleaning_confidence','evidence_reference','notes'],name_corr);write(C/'phase-2-geometry-resolution-register.csv',geom_headers,geom);write(C/'phase-2-operational-status-review.csv',['feature_id','layer_id','source_status','operational_status_code','operational_status_ar','evidence_type','evidence_reference','confidence','institutional_confirmation_required','notes'],op);write(C/'phase-2-investment-legal-review.csv',['feature_id','name_ar','field_availability_status','evidence_reference','ownership_status','legal_status','license_status','investment_value_status','area_status','infrastructure_status','institutional_confirmation_required','notes'],legal);write(C/'phase-2-internal-source-linkage-register.csv',['feature_id','layer_id','source_file','source_sheet_or_section','source_record_identifier','match_type','match_score','matched_fields','conflicting_fields','fields_imported','automatic_import','manual_review_required','notes'],link);write(C/'national-data-cleaning-phase-2-change-log.csv',['change_id','feature_id','layer_id','change_type','field_name','old_value','new_value','reason','evidence_type','evidence_reference','source_case_id','confidence','automatic_change','institutional_confirmation_required','timestamp','reversible','notes'],changelog);write(C/'phase-2-review-closure-register.csv',['review_case_id','feature_id','layer_id','original_priority','original_reason_codes','resolution','fields_resolved','evidence','confidence','publication_status_before','publication_status_after','closed_automatically','closed_date','notes'],closures)

# Metadata, scorecards, GeoJSON. Keep the approved 675-item baseline separate from 29 expanded P2 triage tasks.
p2_official=[];p3_official=[]
for _lid,_row in phase1_by.items():
 p2_official += [x for x in p2 if x['layer_id']==_lid][:int(_row['p2_remaining'])]
 p3_official += [x for x in p3 if x['layer_id']==_lid][:int(_row['p3_remaining'])]
p2=p2_official;p3=p3_official;scores=[];pub=Counter();improved=0
for lid,d in D.items():
 current=[f for f in d['features'] if f['properties'].get('review_status') in ('open','institutional_action_open') or f['properties'].get('data_review_status') in ('review_required','pending_review')];ps=Counter(f['properties'].get('review_priority') for f in current);p1b=sum(x['layer_id']==lid for x in p1);p2b=sum(x['layer_id']==lid for x in p2);p3b=sum(x['layer_id']==lid for x in p3);pd=Counter(f['properties']['publication_status'] for f in d['features']);pub.update(pd);bef=sum(before_scores[f['properties']['id']][0] for f in d['features'])/len(d['features']);aft=sum(f['properties']['weighted_completeness_score'] for f in d['features'])/len(d['features']);bc=sum(before_scores[f['properties']['id']][1] for f in d['features'])/len(d['features']);ac=sum(f['properties']['critical_fields_completeness'] for f in d['features'])/len(d['features']);improved+=sum(f['properties']['weighted_completeness_score']>before_scores[f['properties']['id']][0] for f in d['features']);scores.append({'layer_id':lid,'features_before':START[lid],'features_after':len(d['features']),'new_true_duplicates_merged':0,'probable_duplicates_remaining':sum(x['layer_id']==lid for x in probable),'p1_before':p1b,'p1_resolved':0,'p1_remaining':p1b,'p2_before':p2b,'p2_resolved':0,'p2_remaining':p2b,'p3_before':p3b,'p3_resolved':0,'p3_remaining':p3b,'temporary_names_before':sum(x['layer_id']==lid for x in temp),'temporary_names_resolved':0,'temporary_names_remaining':sum(x['layer_id']==lid for x in temp),'classification_corrections':0,'name_corrections':sum(x['layer_id']==lid for x in name_corr),'geometry_corrections':0,'operational_status_corrections':0,'investment_legal_fields_completed':0,'internal_source_matches':sum(x['layer_id']==lid and x['match_type']=='exact_internal_match' for x in link),'review_items_before':sum(x['layer_id']==lid for x in actions),'review_items_resolved':0,'review_items_remaining':sum(x['layer_id']==lid for x in actions),'completeness_before':round(bef,2),'completeness_after':round(aft,2),'critical_completeness_before':round(bc,2),'critical_completeness_after':round(ac,2),'public_ready':pd['public_ready'],'internal_ready':pd['internal_ready'],'internal_only':pd['internal_only'],'withheld_pending_verification':pd['withheld_pending_verification'],'cleaning_status':'complete_with_institutional_actions'});d['metadata']=dict(d.get('metadata') or {},cleaning_phase='national_data_cleaning_phase_2',cleaning_date=TODAY,features_before=START[lid],features_after=len(d['features']),new_true_duplicates_merged=0,p1_before=p1b,p1_resolved=0,p1_remaining=p1b,review_items_before=sum(x['layer_id']==lid for x in actions),review_items_resolved=0,review_items_remaining=sum(x['layer_id']==lid for x in actions),completeness_before=round(bef,2),completeness_after=round(aft,2),methodology_version='2.0.0');(R/FILES[lid]).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
write(C/'national-data-cleaning-phase-2-scorecard.csv',list(scores[0]),scores);(C/'national-data-cleaning-phase-2-scorecard.json').write_text(json.dumps({'generated_at':NOW,'status':'CLEANING_PHASE_2_COMPLETE_WITH_INSTITUTIONAL_ACTIONS','layers':scores},ensure_ascii=False,indent=2)+'\n',encoding='utf8')
avg_b=sum(x['completeness_before']*x['features_before'] for x in scores)/TOTAL;avg_a=sum(x['completeness_after']*x['features_after'] for x in scores)/TOTAL;crit_b=sum(x['critical_completeness_before']*x['features_before'] for x in scores)/TOTAL;crit_a=sum(x['critical_completeness_after']*x['features_after'] for x in scores)/TOTAL
report=f'''# تقرير تنظيف السجل الوطني — المرحلة الثانية\n\n## الملخص التنفيذي\n\nالحالة: **CLEANING_PHASE_2_COMPLETE_WITH_INSTITUTIONAL_ACTIONS**. بدأ العمل بـ{TOTAL} Feature. لم يثبت تكرار جديد من 104 حالات probable بدليل داخلي مستقل، لذلك لم يُحذف أو يُدمج أي Feature وانتهى العدد بـ{TOTAL}.\n\n## P1 والتكرارات\n\nراجعت {len(p1)} حالة P1، وحُولت جميعها إلى إجراءات مؤسسية مفتوحة مع حجب أو قصر العرض الداخلي؛ لم تُغلق المشكلة الجوهرية بمجرد التوثيق. بقيت حالات probable وعددها {len(probable)} للتأكيد المؤسسي.\n\n## الاسم والتصنيف والهندسة\n\nعولج الاسم المؤقت الوحيد كتسمية إدارية غير رسمية مع `official_name_required=true` و`internal_only`. لم تُنفذ تصحيحات تصنيف أو هندسة دون دليل، ولم يُستنتج التشغيل أو الترخيص أو الملكية من الغياب.\n\n## الاستثمار والمصادر الداخلية\n\nأنشئت حالات توفر منفصلة للحقول القانونية والاستثمارية. سجل الربط الداخلي يثبت روابط المصدر و`source_record_index` دون استيراد قيم إضافية أو رفع الجاهزية.\n\n## الاكتمال والنشر\n\n- المتوسط قبل: {avg_b:.2f}%، وبعد: {avg_a:.2f}%\n- اكتمال الحقول الحرجة قبل: {crit_b:.2f}%، وبعد: {crit_a:.2f}%\n- public_ready: {pub['public_ready']}\n- internal_ready: {pub['internal_ready']}\n- internal_only: {pub['internal_only']}\n- withheld_pending_verification: {pub['withheld_pending_verification']}\n\nلم ترفع metadata التقنية اكتمال البيانات السياحية.\n\n## حزم الإجراءات والمخاطر\n\nأنشئت 12 حزمة موزعة حسب الجهة، ونموذج رد موحد، وملخص إداري. الجهات مطلوبة للاستكمال وليست مصادر مؤكدة. المخاطر المفتوحة: P1، التكرارات المحتملة، الاسم الرسمي، ونقص الحقول القانونية والاستثمارية. المرحلة التالية هي استلام ردود الجهات والتحقق من وثائقها قبل أي دمج.\n''';(R/'docs/national-data-cleaning-phase-2-report.md').write_text(report,encoding='utf8')
print(f'TOTAL_FEATURES_PHASE_2_START = {TOTAL}');print(f'REVIEW_ITEMS_PHASE_2_START = {len(actions)}');print(f'P1_ITEMS_PHASE_2_START = {len(p1)}');print(f'P2_ITEMS_PHASE_2_START = {len(p2)}');print(f'P3_ITEMS_PHASE_2_START = {len(p3)}');print(f'PROBABLE_DUPLICATES_PHASE_2_START = {len(probable)}');print(f'TEMPORARY_NAMES_PHASE_2_START = {len(temp)}');print('NEW_TRUE_DUPLICATE_RECORDS_RETIRED = 0');print(f'TOTAL_FEATURES_PHASE_2_END = {TOTAL}');print('PHASE_2_FEATURE_COUNT_RECONCILIATION = PASS');print(f'AVERAGE_COMPLETENESS_BEFORE_PHASE_2 = {avg_b:.2f}');print(f'AVERAGE_COMPLETENESS_AFTER_PHASE_2 = {avg_a:.2f}');print(f'CRITICAL_COMPLETENESS_BEFORE = {crit_b:.2f}');print(f'CRITICAL_COMPLETENESS_AFTER = {crit_a:.2f}');print(f'FEATURES_WITH_COMPLETENESS_IMPROVEMENT = {improved}')
