from playwright.sync_api import sync_playwright
import json
KEYS={"main":"WH-WORLD-C0004","ain_al_faras":"WH-LY-005-C0004","mosque":"WH-LY-005-C0002","street":"WH-LY-005-C0009","house":"WH-LY-005-C0025","museum":"WH-LY-005-C0011"}
with sync_playwright() as p:
 b=p.chromium.launch(headless=True);page=b.new_page(viewport={"width":1440,"height":1000});errors=[];failed=[];page.on("pageerror",lambda e:errors.append(str(e)));page.on("requestfailed",lambda r:failed.append(r.url));page.goto("http://localhost:8000/?ghadames-complete-test=1",wait_until="domcontentloaded",timeout=60000);page.wait_for_function("typeof window.__atlasTest==='object'");page.wait_for_timeout(900)
 count=page.evaluate("""()=>{let n=0;function w(x){if(!x?.getLayers)return;for(const y of x.getLayers()){const q=y.feature?.properties||{};if(q.id==='WH-WORLD-C0004'||q.parent_site_id==='WH-LY-005')n++;w(y)}};for(const s of Object.values(window.__atlasTest.state))w(s.group);return n}""");print('ALL_GHADAMES_FEATURES_RENDERED =','PASS' if count==29 else 'FAIL',count)
 page.fill('#searchInput','غدامس');page.click('#searchBtn');page.wait_for_timeout(400);print('GHADAMES_SEARCH =','PASS' if 'غدامس' in (page.locator('.leaflet-popup-content').inner_text() if page.locator('.leaflet-popup-content').count() else '') else 'FAIL');page.evaluate("()=>window.__atlasTest.map.closePopup()")
 for label,fid in KEYS.items():
  page.evaluate("()=>window.__atlasTest.map.closePopup()")
  ok=page.evaluate("""id=>{let f;function w(x){if(f||!x?.getLayers)return;for(const y of x.getLayers()){if(y.feature?.properties?.id===id){f=y;return}w(y)}};for(const s of Object.values(window.__atlasTest.state))w(s.group);if(!f)return false;for(const s of Object.values(window.__atlasTest.state))s.group?.removeLayer?.(f);f.addTo(window.__atlasTest.map);f.openPopup();return true}""",fid);page.wait_for_timeout(450);st=page.evaluate("""()=>{const im=[...document.querySelectorAll('.leaflet-popup-content img')];return {real:im.filter(x=>x.dataset.placeholder!=='true'&&x.naturalWidth>0).length,placeholder:im.filter(x=>x.dataset.placeholder==='true').length,broken:im.filter(x=>x.complete&&x.naturalWidth===0).length}}""");print('GHADAMES_'+label.upper()+'_POPUP =',('PASS' if st['real'] else 'NO_CONFIRMED_IMAGE') if ok else 'FAIL',json.dumps(st))
 page.evaluate("()=>window.__atlasTest.map.closePopup()");cfg=page.evaluate("()=>window.__atlasTest.layers.find(x=>x.id==='heritage')");page.evaluate("async cfg=>await toggleLayer(cfg,false)",cfg);page.wait_for_timeout(250);hidden=page.evaluate("()=>window.__atlasTest.map.hasLayer(window.__atlasTest.state.heritage.group)");page.evaluate("async cfg=>await toggleLayer(cfg,true)",cfg);page.wait_for_timeout(500);shown=page.evaluate("()=>window.__atlasTest.map.hasLayer(window.__atlasTest.state.heritage.group)");print('GHADAMES_HIDE_SHOW =','PASS' if not hidden and shown else 'FAIL')
 print('NO_IMAGE_404 =','PASS' if not failed else 'FAIL');print('NO_CONSOLE_ERRORS =','PASS' if not errors else 'FAIL');print('FAILED =',len(failed)+len(errors));b.close()
