from playwright.sync_api import sync_playwright
import json
KEYS={"main":"WH-WORLD-C0002","temple_zeus":"WH-LY-003-C0021","apollo_fountain":"WH-LY-003-C0016","greek_theatre":"WH-LY-003-C0001","roman_theatre":"WH-LY-003-C0013","agora":"WH-LY-003-C0022","baths":"WH-LY-003-C0003","museum":"WH-LY-003-C0002","necropolis":"WH-LY-003-C0027"}
with sync_playwright() as p:
 b=p.chromium.launch(headless=True);page=b.new_page(viewport={"width":1440,"height":1000});errors=[];failed=[];page.on("pageerror",lambda e:errors.append(str(e)));page.on("requestfailed",lambda r:failed.append(r.url));page.goto("http://localhost:8000/?cyrene-complete-test=1",wait_until="domcontentloaded",timeout=60000);page.wait_for_function("typeof window.__atlasTest==='object'");page.wait_for_timeout(900)
 count=page.evaluate("""()=>{let n=0;function w(x){if(!x?.getLayers)return;for(const y of x.getLayers()){const q=y.feature?.properties||{};if(q.id==='WH-WORLD-C0002'||q.parent_site_id==='WH-LY-003')n++;w(y)}};for(const s of Object.values(window.__atlasTest.state))w(s.group);return n}""");print('ALL_CYRENE_FEATURES_RENDERED =','PASS' if count==29 else 'FAIL',count)
 main=page.evaluate("id=>{let f;function w(x){if(f||!x?.getLayers)return;for(const y of x.getLayers()){if(y.feature?.properties?.id===id){f=y;return}w(y)}};for(const st of Object.values(window.__atlasTest.state))w(st.group);if(!f)return null;for(const st of Object.values(window.__atlasTest.state))st.group?.removeLayer?.(f);f.addTo(window.__atlasTest.map);f.openPopup();return f.feature?.properties||null}",'WH-WORLD-C0002');page.wait_for_timeout(500);m=page.evaluate("()=>({title:document.querySelector('.popup-title')?.innerText||'',real:[...document.querySelectorAll('.leaflet-popup-content img')].filter(x=>x.dataset.placeholder!=='true'&&x.naturalWidth>0).length})");print('CYRENE_MAIN_DATA_PRESENT =','PASS' if main and m['title'] and main.get('name_ar') and main.get('description_ar') else 'FAIL');print('CYRENE_MAIN_REAL_IMAGE =','PASS' if m['real']>0 else 'FAIL');page.evaluate("()=>window.__atlasTest.map.closePopup()")
 for label,fid in KEYS.items():
  page.evaluate("()=>window.__atlasTest.map.closePopup()")
  ok=page.evaluate("""id=>{let f;function w(x){if(f||!x?.getLayers)return;for(const y of x.getLayers()){if(y.feature?.properties?.id===id){f=y;return}w(y)}};for(const s of Object.values(window.__atlasTest.state))w(s.group);if(!f)return false;for(const s of Object.values(window.__atlasTest.state))s.group?.removeLayer?.(f);f.addTo(window.__atlasTest.map);f.openPopup();return true}""",fid);page.wait_for_timeout(500);st=page.evaluate("""()=>{const im=[...document.querySelectorAll('.leaflet-popup-content img')];return {real:im.filter(x=>x.dataset.placeholder!=='true'&&x.naturalWidth>0).length,placeholder:im.filter(x=>x.dataset.placeholder==='true').length,broken:im.filter(x=>x.complete&&x.naturalWidth===0).length}}""");print('CYRENE_'+label.upper()+'_POPUP =',('PASS' if st['real'] else 'NO_CONFIRMED_IMAGE') if ok else 'FAIL',json.dumps(st))
 page.fill('#searchInput','معبد زيوس في قورينا');page.click('#searchBtn');page.wait_for_timeout(500);print('CYRENE_SEARCH_ZEUS =','PASS' if 'معبد زيوس' in (page.locator('.leaflet-popup-content').inner_text() if page.locator('.leaflet-popup-content').count() else '') else 'FAIL');page.evaluate("()=>window.__atlasTest.map.closePopup()")
 cfg=page.evaluate("()=>window.__atlasTest.layers.find(x=>x.id==='heritage')");page.evaluate("async cfg=>await toggleLayer(cfg,false)",cfg);page.wait_for_timeout(250);hidden=page.evaluate("()=>window.__atlasTest.map.hasLayer(window.__atlasTest.state.heritage.group)");page.evaluate("async cfg=>await toggleLayer(cfg,true)",cfg);page.wait_for_timeout(600);shown=page.evaluate("()=>window.__atlasTest.map.hasLayer(window.__atlasTest.state.heritage.group)");print('CYRENE_HIDE_SHOW =','PASS' if not hidden and shown else 'FAIL',hidden,shown)
 print('NO_IMAGE_404 =','PASS' if not failed else 'FAIL');print('NO_CONSOLE_ERRORS =','PASS' if not errors else 'FAIL');print('FAILED =',len(failed)+len(errors));b.close()
