import sys
sys.stdout.reconfigure(encoding='utf-8')
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
 b=p.chromium.launch(headless=True);page=b.new_page(viewport={'width':1440,'height':1000});errors=[];bad=[];page.on('pageerror',lambda e:errors.append(str(e)));page.on('response',lambda r: bad.append((r.status,r.url)) if r.status>=400 else None);page.goto('http://localhost:8000/?cyrene-accurate-image-linkage=1',wait_until='domcontentloaded',timeout=60000);page.wait_for_function("typeof window.__atlasTest==='object'");page.wait_for_timeout(800)
 out=page.evaluate("""async()=>{const d=await (await fetch('data/layers/world-heritage.geojson')).json();const fs=d.features.filter(f=>f.id==='WH-WORLD-C0002'||f.properties?.parent_site_id==='WH-LY-003');let layers=[];function w(x){if(!x?.getLayers)return;for(const y of x.getLayers()){if(y.feature?.properties?.id)layers.push(y);w(y)}};for(const s of Object.values(window.__atlasTest.state||{}))w(s.group);let exact=0,general=0,placeholder=0,failed=0;const details=[];for(const f of fs){const l=layers.find(x=>x.feature?.properties?.id===f.id);window.__atlasTest.map.closePopup();if(l){l.addTo(window.__atlasTest.map);l.fire('click')}await new Promise(r=>setTimeout(r,120));const cs=[...document.querySelectorAll('.leaflet-popup-content')],c=cs.at(-1),im=[...(c?.querySelectorAll('img')||[])];const real=im.filter(i=>i.dataset.placeholder!=='true'&&i.naturalWidth>0&&i.naturalHeight>0);const ph=im.filter(i=>i.dataset.placeholder==='true');const type=f.properties?.image_match_type||'placeholder';if(type==='exact_feature'||type==='high_confidence_feature')exact+=real.length?1:0;else if(type==='site_general')general+=real.length?1:0;else placeholder+=ph.length?1:0;if(!c?.querySelector('.popup-title')||(!real.length&&!ph.length))failed++;details.push({id:f.id,title:c?.querySelector('.popup-title')?.innerText||'',image_type:type,src:real[0]?.currentSrc||'',placeholder:!!ph.length,width:real[0]?.naturalWidth||0,height:real[0]?.naturalHeight||0})}return {total:fs.length,exact,general,placeholder,failed,details}}""")
 for d in out['details']:
  if d['id'] in ('WH-WORLD-C0002','WH-LY-003-C0005','WH-LY-003-C0021'): print('FEATURE',d)
 print('CYRENE_POPUPS_TESTED =',out['total']);print('CYRENE_POPUPS_WITH_EXACT_IMAGES =',out['exact']);print('CYRENE_POPUPS_WITH_GENERAL_IMAGES =',out['general']);print('CYRENE_POPUPS_WITH_PLACEHOLDER =',out['placeholder']);zeus=next(d for d in out['details'] if d['id']=='WH-LY-003-C0021');print('ZEUS_TEMPLE_IMAGE_ACCURATE =','PASS' if zeus['image_type']=='exact_feature' and 'cyrene-temple-of-zeus' in zeus['src'] and not 'aerial' in zeus['src'] and zeus['width']>0 else 'FAIL');print('CYRENE_GENERAL_IMAGE_NOT_REPEATED_ACROSS_ALL =','PASS' if out['general']<=5 else 'FAIL');print('NO_IMAGE_404 =','PASS' if not bad else 'FAIL');print('NO_CONSOLE_ERRORS =','PASS' if not errors else 'FAIL');print('FAILED =',out['failed']+len(bad)+len(errors));b.close()
