import sys
sys.stdout.reconfigure(encoding='utf-8')
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
 b=p.chromium.launch(headless=True);page=b.new_page(viewport={'width':1440,'height':1000});errors=[];failed=[];bad_responses=[];page.on('pageerror',lambda e:errors.append(str(e)));page.on('requestfailed',lambda r:failed.append(r.url));page.on('response',lambda r: bad_responses.append((r.status,r.url)) if r.status>=400 else None);page.goto('http://localhost:8000/?world-heritage-complete-image-linkage=1',wait_until='domcontentloaded',timeout=60000);page.wait_for_function("typeof window.__atlasTest==='object'");page.wait_for_timeout(800)
 result=page.evaluate("""async()=>{
   const groups={LEPTIS:f=>f.id==='WH-MAIN-001'||f.properties?.parent_site_id==='WH-MAIN-001',SABRATHA:f=>f.id==='WH-WORLD-C0001'||f.properties?.parent_site_id==='WH-LY-002',CYRENE:f=>f.id==='WH-WORLD-C0002'||f.properties?.parent_site_id==='WH-LY-003',GHADAMES:f=>f.id==='WH-WORLD-C0004'||f.properties?.parent_site_id==='WH-LY-005',AKAKUS:f=>f.id==='WH-WORLD-C0003'||f.properties?.parent_site_id==='WH-LY-004'};
   const layers=[];function walk(x){if(!x?.getLayers)return;for(const y of x.getLayers()){if(y.feature?.properties?.id)layers.push(y);walk(y)}};for(const s of Object.values(window.__atlasTest.state||{}))walk(s.group);
   const out=Object.fromEntries(Object.keys(groups).map(k=>[k,{tested:0,real:0,placeholder:0,failed:0}]));
   for(const [site,fn] of Object.entries(groups)) for(const l of layers){const f=l.feature;if(!fn(f))continue;out[site].tested++;window.__atlasTest.map.closePopup();l.addTo(window.__atlasTest.map);l.fire('click');await new Promise(r=>setTimeout(r,120));const cs=[...document.querySelectorAll('.leaflet-popup-content')];const c=cs.at(-1);const imgs=[...(c?.querySelectorAll('img')||[])];const real=imgs.filter(i=>i.dataset.placeholder!=='true'&&i.naturalWidth>0&&i.naturalHeight>0).length;const ph=imgs.filter(i=>i.dataset.placeholder==='true').length;const broken=imgs.filter(i=>i.complete&&i.naturalWidth===0).length;if(!c?.querySelector('.popup-title')||broken||(!real&&!ph)){out[site].failed++;(out[site].failed_ids||(out[site].failed_ids=[])).push(f.id);}else if(real)out[site].real++;else out[site].placeholder++;}
   return out;
 }""")
 for s,c in result.items(): print(s+'_POPUPS_TESTED =',c['tested']);print(s+'_POPUPS_WITH_REAL_IMAGES =',c['real']);print(s+'_POPUPS_WITH_PLACEHOLDER =',c['placeholder']);print(s+'_POPUPS_FAILED =',c['failed'])
 ain=page.evaluate("""()=>{let f;function w(x){if(f||!x?.getLayers)return;for(const y of x.getLayers()){if(y.feature?.properties?.id==='WH-LY-005-C0004'){f=y;return}w(y)}};for(const s of Object.values(window.__atlasTest.state||{}))w(s.group);if(!f)return false;f.addTo(window.__atlasTest.map);f.fire('click');return true}""");page.wait_for_timeout(100);ain_real=page.evaluate("()=>[...document.querySelectorAll('.leaflet-popup-content:last-child img')].some(x=>x.dataset.placeholder!=='true'&&x.naturalWidth>0&&x.naturalHeight>0)")
 print('AIN_AL_FARAS_REAL_IMAGE =','PASS' if ain and ain_real else 'FAIL');print('FAILED_RESPONSE_URLS =',bad_responses[:10]);print('FAILED_REQUEST_URLS =',failed[:10]);print('NO_IMAGE_404 =','PASS' if not bad_responses else 'FAIL');print('NO_CONSOLE_ERRORS =','PASS' if not errors else 'FAIL');total_failed=sum(c['failed'] for c in result.values())+len(failed)+len(errors);print('FAILED =',total_failed);b.close()
