import sys,time
from playwright.sync_api import sync_playwright
sys.stdout.reconfigure(encoding='utf-8');ROOT='http://127.0.0.1:8766/';SAMPLES=['كافي 92','مقهى الركن السياحي ( مقهى ارقيلة شيشة )','JOE & THE JUICE LIBYA','مقهى ومطعم فلانيل','أورزو للأيسكريم orso ice cream'];results={};failures=[];console_errors=[];image_404=[];remote=[]
with sync_playwright() as pw:
 browser=pw.chromium.launch(headless=True);page=browser.new_page(viewport={'width':1440,'height':1000});page.on('console',lambda m:console_errors.append(m.text) if m.type=='error' else None);page.on('response',lambda r:image_404.append(r.url) if r.status==404 and r.request.resource_type=='image' else None);page.on('request',lambda r:remote.append(r.url) if r.resource_type=='image' and ('googleusercontent' in r.url or 'mymaps.usercontent.google.com' in r.url) else None);page.goto(ROOT+'?tripoli-cafes-layer-test=1',wait_until='domcontentloaded',timeout=60000);page.wait_for_function("typeof window.__atlasTest === 'object'");start=time.perf_counter();page.locator("input[data-id='tripoliCafes']").evaluate("el=>{el.checked=true;el.dispatchEvent(new Event('change',{bubbles:true}))}");page.wait_for_function("window.__atlasTest.state.tripoliCafes?.count === 404",timeout=60000);elapsed=time.perf_counter()-start;state=page.evaluate("()=>{const s=window.__atlasTest.state.tripoliCafes;return{count:s.count,clustered:!!s.pointCluster}}");results['CAFES_LAYER_LOAD']=state['count']==404;results['CAFES_FEATURE_COUNT']=state['count'];results['CAFES_CLUSTERING']=state['clustered'];page.locator("input[data-id='tripoliCafes']").evaluate("el=>{el.checked=false;el.dispatchEvent(new Event('change',{bubbles:true}))}");hidden=page.evaluate("!window.__atlasTest.map.hasLayer(window.__atlasTest.state.tripoliCafes.group)");page.locator("input[data-id='tripoliCafes']").evaluate("el=>{el.checked=true;el.dispatchEvent(new Event('change',{bubbles:true}))}");shown=page.evaluate("window.__atlasTest.map.hasLayer(window.__atlasTest.state.tripoliCafes.group)");results['CAFES_TOGGLE']=hidden and shown
 for i,target in enumerate(SAMPLES,1):
  popup=page.evaluate("""target=>{const s=window.__atlasTest.state.tripoliCafes;let found=null;s.pointCluster.eachLayer(l=>{if(!found&&l.feature?.properties?.name_ar===target)found=l});if(!found)return null;s.pointCluster.removeLayer(found);found.addTo(window.__atlasTest.map);found.openPopup();const d=document.createElement('div');d.innerHTML=found.getPopup()?.getContent?.()||'';return d.innerText}""",target);results[f'CAFE_SAMPLE_{i}_POPUP']=bool(popup and target in popup and 'null' not in popup.lower() and 'undefined' not in popup.lower() and '<![cdata[' not in popup.lower())
 results['NO_RAW_HTML']=all(results.get(f'CAFE_SAMPLE_{i}_POPUP') for i in range(1,6));results['NO_EAGER_REMOTE_IMAGE_LOADING']=not remote;results['NO_IMAGE_404']=not image_404;results['NO_CONSOLE_ERRORS']=not console_errors;results['CAFES_INITIAL_RENDER_PERFORMANCE']=elapsed<10;browser.close()
for key in ['CAFES_LAYER_LOAD','CAFES_TOGGLE','CAFES_CLUSTERING',*[f'CAFE_SAMPLE_{i}_POPUP' for i in range(1,6)],'NO_RAW_HTML','NO_EAGER_REMOTE_IMAGE_LOADING','NO_IMAGE_404','NO_CONSOLE_ERRORS','CAFES_INITIAL_RENDER_PERFORMANCE']:
 if not results.get(key):failures.append(key)
print('CAFES_LAYER_LOAD =','PASS' if results.get('CAFES_LAYER_LOAD') else 'FAIL');print('CAFES_FEATURE_COUNT =',results.get('CAFES_FEATURE_COUNT',0));print('CAFES_TOGGLE =','PASS' if results.get('CAFES_TOGGLE') else 'FAIL');print('CAFES_CLUSTERING =','PASS' if results.get('CAFES_CLUSTERING') else 'FAIL')
for i in range(1,6):print(f'CAFE_SAMPLE_{i}_POPUP =','PASS' if results.get(f'CAFE_SAMPLE_{i}_POPUP') else 'FAIL')
for key in ['NO_RAW_HTML','NO_EAGER_REMOTE_IMAGE_LOADING','NO_IMAGE_404','NO_CONSOLE_ERRORS','CAFES_INITIAL_RENDER_PERFORMANCE']:print(f'{key} =','PASS' if results.get(key) else 'FAIL')
print('FAILED =',len(failures));
if failures:print('\n'.join(failures),file=sys.stderr);sys.exit(1)
